import { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, Chip, Container, Grid, MenuItem, Pagination, Skeleton, Stack, TextField, Typography } from "@mui/material";
import { Link as RouterLink } from "react-router-dom";
import api from "../api/axios";
import { useNotify } from "../context/NotificationContext";

const categories = { idea: "Idea", problem: "Problem", praise: "Praise", other: "Other" };
export default function AdminFeedbackPage() {
    const [items, setItems] = useState([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1);
    const [status, setStatus] = useState(""); const [category, setCategory] = useState(""); const [q, setQ] = useState(""); const [query, setQuery] = useState("");
    const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updating, setUpdating] = useState("");
    const [overview, setOverview] = useState(null);
    const notify = useNotify();
    useEffect(() => { const timer = setTimeout(() => { setQuery(q.trim()); setPage(1); }, 350); return () => clearTimeout(timer); }, [q]);
    const load = useCallback(async () => { try { setLoading(true); setError(""); const { data } = await api.get("/admin/feedback", { params: { page, limit: 20, status: status || undefined, category: category || undefined, q: query || undefined } }); setItems(data.items || []); setTotalPages(data.totalPages || 1); } catch (e) { setError(e?.response?.status === 403 ? "Administrator access is required." : "Feedback could not be loaded."); } finally { setLoading(false); } }, [page, status, category, query]);
    useEffect(() => { load(); }, [load]);
    useEffect(() => { api.get("/admin/overview").then(({ data }) => setOverview(data)).catch(() => {}); }, []);
    const updateStatus = async (id, nextStatus) => { try { setUpdating(id); const { data } = await api.patch(`/admin/feedback/${id}`, { status: nextStatus }); setItems((current) => current.map((item) => item._id === id ? data : item)); notify(`Feedback marked ${nextStatus}.`, "success"); } catch (e) { notify(e?.response?.data?.message || "Status could not be updated.", "error"); } finally { setUpdating(""); } };
    return <Container maxWidth="lg" sx={{ py: { xs: 3, md: 5 } }}>
        <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", sm: "center" }} gap={1}><Box><Typography variant="overline" color="primary.main" fontWeight={850}>Admin</Typography><Typography component="h1" variant="h3" fontWeight={850}>Product feedback</Typography></Box><Button component={RouterLink} to="/admin/audit" variant="outlined">View audit activity</Button></Stack><Typography color="text.secondary" mt={1} mb={3}>Review user-submitted ideas, problems, and praise. Status changes are written to the audit log.</Typography>
        {overview && <><Typography component="h2" variant="h5" fontWeight={800} mb={2}>Operating overview</Typography><Grid container spacing={2} mb={4}>{[
            ["Users", overview.users], ["Verified users", overview.verifiedUsers], ["Active sessions", overview.activeSessions], ["Interviews", overview.interviews], ["Completed interviews", overview.completedInterviews], ["New feedback", overview.newFeedback], ["Failed reminders", overview.failedReminders], ["30-day activations", overview.events?.interview_created || 0],
        ].map(([label,value]) => <Grid size={{ xs: 6, md: 3 }} key={label}><Card variant="outlined"><CardContent><Typography variant="h5" fontWeight={850}>{value}</Typography><Typography variant="body2" color="text.secondary">{label}</Typography></CardContent></Card></Grid>)}</Grid></>}
        {error && <Alert severity="error" onClose={() => setError("")} sx={{ mb: 2 }}>{error}</Alert>}
        <Grid container spacing={2} mb={3}><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth label="Search feedback" value={q} onChange={(e) => setQ(e.target.value)} /></Grid><Grid size={{ xs: 6, md: 3 }}><TextField select fullWidth label="Category" value={category} onChange={(e) => { setCategory(e.target.value); setPage(1); }}><MenuItem value="">All</MenuItem>{Object.entries(categories).map(([value,label]) => <MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Grid><Grid size={{ xs: 6, md: 3 }}><TextField select fullWidth label="Status" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><MenuItem value="">All</MenuItem>{["new","reviewed","closed"].map((value) => <MenuItem key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</MenuItem>)}</TextField></Grid></Grid>
        {loading ? <Stack spacing={2}>{[1,2,3].map((item) => <Skeleton key={item} variant="rounded" height={150} />)}</Stack> : items.length === 0 ? <Alert severity="info">No feedback matches these filters.</Alert> : <Stack spacing={2}>{items.map((item) => <Card key={item._id} variant="outlined"><CardContent><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" spacing={2}><Box flex={1}><Stack direction="row" spacing={1} mb={1}><Chip size="small" label={categories[item.category] || item.category} /><Chip size="small" variant="outlined" label={item.status} /></Stack><Typography sx={{ whiteSpace: "pre-wrap" }}>{item.message}</Typography>{!!item.photos?.length && <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap mt={1.5}>{item.photos.map((photo, index) => <Box key={photo.publicId || index} component="a" href={photo.url} target="_blank" rel="noreferrer noopener"><Box component="img" src={photo.url} alt={`Attachment ${index + 1}`} sx={{ width: 72, height: 72, objectFit: "cover", borderRadius: 1, border: "1px solid", borderColor: "divider" }} /></Box>)}</Stack>}<Typography variant="caption" color="text.secondary" display="block" mt={2}>{item.user?.name || "Deleted user"} · {item.user?.email || "Account unavailable"} · {new Date(item.createdAt).toLocaleString()} · {item.page || "Unknown page"}</Typography></Box><TextField select size="small" label="Status" value={item.status} disabled={updating === item._id} onChange={(e) => updateStatus(item._id, e.target.value)} sx={{ minWidth: 140 }}>{["new","reviewed","closed"].map((value) => <MenuItem key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</MenuItem>)}</TextField></Stack></CardContent></Card>)}</Stack>}
        {totalPages > 1 && <Stack alignItems="center" mt={3}><Pagination page={page} count={totalPages} onChange={(_, value) => setPage(value)} /></Stack>}
    </Container>;
}
