export const PRODUCT_RESOURCE_PAGES = [
    {
        surface: "practice",
        slug: "system-design-interview-questions",
        title: "System Design Interview Questions",
        metaTitle: "System Design Interview Questions for Software Engineers | Evalcue AI",
        description: "Practice realistic system design interview questions with role-specific context, architecture trade-offs, follow-up discussion, and structured feedback.",
        eyebrow: "Interactive system design practice",
        intro: "Choose a common system-design problem and open it as a real Evalcue AI practice session. The role and problem context are carried into the interview builder for you.",
        roles: ["Software Engineer II", "Senior Software Engineer", "Backend Engineer"],
        examples: [
            { id: "url-shortener", title: "Design a URL shortener", summary: "APIs, key generation, storage, caching, redirects, and hot-key handling.", jobDescription: "You are preparing for a system design interview. Design a production URL-shortening service. Cover requirements, APIs, data model, short-code generation, redirects, caching, scaling, availability, abuse prevention, observability, and trade-offs." },
            { id: "notifications", title: "Design a notification service", summary: "Fan-out, queues, retries, preferences, rate limits, and delivery guarantees.", jobDescription: "You are preparing for a system design interview. Design a global notification platform for push, email, and SMS. Cover APIs, queues, retries, idempotency, user preferences, rate limiting, delivery tracking, failure handling, scale, and trade-offs." },
            { id: "drive", title: "Design cloud file storage", summary: "Uploads, metadata, chunking, versioning, sharing, sync, and consistency.", jobDescription: "You are preparing for a system design interview. Design a Google Drive-like file storage and synchronization service. Cover upload APIs, chunking, metadata, object storage, sharing, permissions, versioning, sync, consistency, reliability, and scale." },
        ],
        related: ["system-design-interview-preparation", "sde-2-interview-preparation", "software-engineer-mock-interview"],
    },
    {
        surface: "practice",
        slug: "java-interview-questions",
        title: "Java Interview Questions",
        metaTitle: "Java Interview Questions & Practice for Software Engineers | Evalcue AI",
        description: "Prepare for Java interviews with questions on the JVM, collections, concurrency, exceptions, OOP, memory, and practical backend engineering.",
        eyebrow: "Java interview practice",
        intro: "Pick a Java interview track and start a role-specific mock interview instead of only reading answers.",
        roles: ["Java Backend Engineer", "Software Engineer II", "Senior Java Engineer"],
        examples: [
            { id: "core-java", title: "Core Java", summary: "JVM, memory, OOP, exceptions, strings, generics, and language fundamentals.", jobDescription: "Run a Java technical interview covering JVM/JDK/JRE, memory model, OOP, interfaces vs abstract classes, exceptions, strings, generics, immutability, pass-by-value, and practical Java reasoning. Ask adaptive follow-ups rather than trivia only." },
            { id: "collections-concurrency", title: "Collections + concurrency", summary: "HashMap internals, concurrent collections, locks, executors, futures, and thread safety.", jobDescription: "Run a Java backend interview focused on collections and concurrency. Cover HashMap internals, equality/hashCode, concurrent collections, synchronization, locks, executors, CompletableFuture, race conditions, deadlocks, and production thread-safety trade-offs." },
            { id: "spring-backend", title: "Java backend engineering", summary: "Spring, APIs, transactions, caching, databases, resilience, and testing.", jobDescription: "Run a Java backend engineering interview focused on Spring services, REST APIs, dependency injection, transactions, database access, caching, resilience, observability, testing, and design trade-offs. Include scenario-based follow-ups." },
        ],
        related: ["coding-interview-questions", "sde-2-interview-preparation", "software-engineer-mock-interview"],
    },
    {
        surface: "practice",
        slug: "software-engineer-mock-interview",
        title: "Software Engineer Mock Interview",
        metaTitle: "Software Engineer Mock Interview Online | Evalcue AI",
        description: "Run a realistic software engineering mock interview with adaptive technical questions, coding, system design, and evidence-backed feedback.",
        eyebrow: "Start a real mock interview",
        intro: "Choose the level you are targeting. Evalcue AI opens the actual practice builder with that interview target already filled in.",
        roles: ["Software Engineer I", "Software Engineer II", "Senior Software Engineer"],
        examples: [
            { id: "backend", title: "Backend mock", summary: "APIs, databases, caching, queues, reliability, coding, and debugging.", jobDescription: "Run a realistic backend software engineering mock interview. Evaluate coding, API design, databases, caching, asynchronous processing, reliability, debugging, observability, testing, and engineering trade-offs with adaptive follow-ups." },
            { id: "full-stack", title: "Full-stack mock", summary: "Frontend, APIs, data, performance, testing, and end-to-end ownership.", jobDescription: "Run a realistic full-stack software engineering mock interview. Evaluate frontend architecture, APIs, data modeling, performance, accessibility, testing, security, deployment, and end-to-end product ownership with adaptive follow-ups." },
            { id: "platform", title: "Platform / distributed systems", summary: "Scalability, reliability, infrastructure, observability, and system design.", jobDescription: "Run a realistic platform engineering mock interview focused on distributed systems, scalability, reliability, caching, queues, observability, failure modes, deployment, infrastructure trade-offs, and system design." },
        ],
        related: ["sde-2-interview-preparation", "system-design-interview-questions", "coding-interview-questions"],
    },
    {
        surface: "practice",
        slug: "sde-2-interview-preparation",
        title: "SDE-2 Interview Preparation",
        metaTitle: "SDE-2 Interview Preparation Roadmap & Mock Practice | Evalcue AI",
        description: "Prepare for SDE-2 interviews across coding, low-level design, system design, debugging, behavioral discussion, and technical depth.",
        eyebrow: "SDE-2 preparation",
        intro: "Use the roadmap as a starting point, then launch the section you want to practice as an actual interview session.",
        roles: ["Software Engineer II", "SDE-2", "Senior Software Engineer"],
        examples: [
            { id: "balanced", title: "Balanced SDE-2 loop", summary: "Coding, design, production reasoning, and behavioral depth.", jobDescription: "Prepare for an SDE-2 interview loop. Include coding problem solving, object-oriented/low-level design, system design, debugging and production reasoning, ownership, trade-offs, testing, and behavioral follow-ups appropriate for an experienced engineer." },
            { id: "design-heavy", title: "Design-heavy loop", summary: "LLD, HLD, APIs, storage, scaling, reliability, and trade-offs.", jobDescription: "Prepare for a design-heavy SDE-2 interview. Focus on low-level design, APIs, object modeling, system design, data stores, caching, queues, scaling, consistency, reliability, observability, and explicit trade-offs." },
            { id: "backend-heavy", title: "Backend-heavy loop", summary: "Java/backend depth, distributed systems, databases, and coding.", jobDescription: "Prepare for a backend-focused SDE-2 interview. Cover Java/backend engineering, coding, databases, transactions, caching, distributed systems, queues, reliability, observability, API design, and system design." },
        ],
        related: ["system-design-interview-preparation", "java-interview-questions", "coding-interview-questions"],
    },
    {
        surface: "practice",
        slug: "system-design-interview-preparation",
        title: "System Design Interview Preparation",
        metaTitle: "System Design Interview Preparation Guide & Practice | Evalcue AI",
        description: "Prepare for system design interviews using a repeatable requirements, API, data model, architecture, scale, reliability, and trade-off framework.",
        eyebrow: "System design framework + practice",
        intro: "Choose a design focus and launch it into the live interview flow, where follow-ups can challenge your assumptions and trade-offs.",
        roles: ["Software Engineer II", "Senior Backend Engineer", "Senior Software Engineer"],
        examples: [
            { id: "framework", title: "Full interview framework", summary: "Requirements → estimates → APIs → data → architecture → bottlenecks → trade-offs.", jobDescription: "Run a complete system design interview. Require clarification of functional and non-functional requirements, rough scale estimates, API design, data model, high-level architecture, bottlenecks, caching, queues, consistency, availability, observability, security, and explicit trade-offs." },
            { id: "scalability", title: "Scalability & reliability", summary: "Capacity, partitioning, replication, caching, queues, failure modes, and recovery.", jobDescription: "Run a system design interview emphasizing scalability and reliability. Probe capacity estimates, partitioning, replication, caching, queues, backpressure, failover, idempotency, disaster recovery, observability, and graceful degradation." },
            { id: "data", title: "Data & consistency", summary: "Schema, indexes, transactions, consistency models, storage choices, and hotspots.", jobDescription: "Run a system design interview emphasizing data architecture. Probe schema design, access patterns, indexes, transactions, SQL vs NoSQL choices, consistency, replication, partitioning, hotspot avoidance, caching, and data lifecycle." },
        ],
        related: ["system-design-interview-questions", "sde-2-interview-preparation", "software-engineer-mock-interview"],
    },
    {
        surface: "practice",
        slug: "coding-interview-questions",
        title: "Coding Interview Questions",
        metaTitle: "Coding Interview Questions & Mock Practice | Evalcue AI",
        description: "Practice coding interview questions by topic with role context, explanation follow-ups, complexity discussion, testing, and interview-style feedback.",
        eyebrow: "Coding interview practice",
        intro: "Choose a topic and open a coding-focused interview plan. The session is configured to test reasoning, implementation, complexity, and edge cases—not just the final answer.",
        roles: ["Software Engineer", "Software Engineer II", "Backend Engineer"],
        examples: [
            { id: "arrays-hashing", title: "Arrays + hashing", summary: "Frequency maps, prefix techniques, two pointers, sliding windows, and edge cases.", jobDescription: "Run a coding interview focused on arrays and hashing. Use medium interview problems involving frequency maps, prefix techniques, two pointers, sliding windows, edge cases, complexity analysis, and follow-up optimization." },
            { id: "trees-graphs", title: "Trees + graphs", summary: "Traversal, BFS/DFS, shortest paths, topological reasoning, and complexity.", jobDescription: "Run a coding interview focused on trees and graphs. Cover DFS/BFS, traversal state, shortest paths, topological reasoning, recursion vs iteration, complexity, correctness, and edge cases with adaptive follow-ups." },
            { id: "dynamic-programming", title: "Dynamic programming", summary: "State definition, transitions, memoization, tabulation, and space optimization.", jobDescription: "Run a coding interview focused on dynamic programming. Probe state definition, recurrence, memoization vs tabulation, base cases, complexity, space optimization, and how to derive the solution rather than memorize patterns." },
        ],
        related: ["java-interview-questions", "software-engineer-mock-interview", "sde-2-interview-preparation"],
    },
    {
        surface: "hiring",
        slug: "technical-interview-scorecard-template",
        title: "Technical Interview Scorecard Template",
        metaTitle: "Technical Interview Scorecard Template for Engineering Hiring | Evalcue AI",
        description: "Build a structured engineering interview scorecard and turn it into a draft candidate assessment with evidence-focused technical questions.",
        eyebrow: "Interactive hiring template",
        intro: "Choose a scorecard emphasis and create a real draft assessment in Evalcue AI Hire. Your team can review and edit it before any candidate sees it.",
        roles: ["Software Engineer", "Backend Engineer", "Senior Software Engineer"],
        examples: [
            { id: "balanced-scorecard", title: "Balanced engineering scorecard", summary: "Problem solving, coding, design, reliability, communication, and trade-offs.", jobDescription: "Evaluate an engineer on problem solving, implementation quality, system design, reliability, testing, communication, and explicit trade-offs.", rounds: [{ name: "Technical interview", description: "Collect evidence across implementation, design, debugging, and engineering judgment.", deliveryMode: "conversational", questionCount: 3, questions: [{ text: "Walk through a difficult technical problem you solved. What alternatives did you reject and why?" }, { text: "How would you design and test a service that must remain reliable during partial dependency failures?" }, { text: "Describe a production bug you would investigate methodically. What evidence would you collect first?" }] }] },
            { id: "backend-scorecard", title: "Backend scorecard", summary: "APIs, data, concurrency, resilience, observability, and maintainability.", jobDescription: "Evaluate a backend engineer on API design, data modeling, concurrency, reliability, observability, testing, performance, and maintainability.", rounds: [{ name: "Backend engineering", description: "Evaluate practical backend design and production reasoning.", deliveryMode: "conversational", questionCount: 3, questions: [{ text: "Design an idempotent API for a write operation that clients may retry." }, { text: "How would you diagnose a sudden increase in p99 latency when average latency is unchanged?" }, { text: "When would you choose a queue over a synchronous service call? Explain the failure trade-offs." }] }] },
            { id: "senior-scorecard", title: "Senior engineer scorecard", summary: "Architecture, ambiguity, ownership, incidents, influence, and long-term trade-offs.", jobDescription: "Evaluate a senior engineer on architecture, handling ambiguity, ownership, incident leadership, technical influence, mentoring, and long-term engineering trade-offs.", rounds: [{ name: "Senior engineering judgment", description: "Evaluate architecture and ownership through evidence-rich scenarios.", deliveryMode: "conversational", questionCount: 3, questions: [{ text: "Tell me about an architectural decision you changed after new evidence. What changed your mind?" }, { text: "How would you lead a high-severity incident when the root cause is still unclear?" }, { text: "Describe a case where the technically cleanest solution was not the right business decision." }] }] },
        ],
        related: ["structured-technical-interviews", "technical-assessment-template", "system-design-interview-rubric"],
    },
    {
        surface: "hiring",
        slug: "system-design-interview-rubric",
        title: "System Design Interview Rubric",
        metaTitle: "System Design Interview Rubric & Assessment Template | Evalcue AI",
        description: "Use a structured system design interview rubric covering requirements, APIs, data, architecture, scale, reliability, and trade-offs, then create a real assessment draft.",
        eyebrow: "System design hiring rubric",
        intro: "Select the seniority you are hiring for and create a draft system-design assessment that your hiring team can review before inviting candidates.",
        roles: ["Software Engineer II", "Senior Software Engineer", "Staff Software Engineer"],
        examples: [
            { id: "sde2-system-design", title: "SDE-2 rubric", summary: "Requirements, core architecture, APIs, data model, bottlenecks, and basic reliability.", jobDescription: "Evaluate SDE-2 system design ability: clarify requirements, define APIs and data model, propose a coherent architecture, identify bottlenecks, reason about scale and failure modes, and discuss trade-offs.", rounds: [{ name: "System design", description: "Design a scalable service and explain requirements, APIs, storage, architecture, reliability, and trade-offs.", deliveryMode: "system-design", questionCount: 1, questions: [{ text: "Design a global notification service that supports push, email, and SMS with retries, preferences, and delivery tracking." }] }] },
            { id: "senior-system-design", title: "Senior rubric", summary: "Scale estimates, partitioning, consistency, reliability, observability, and evolution.", jobDescription: "Evaluate senior system design ability: quantify scale, choose storage and partitioning strategies, reason about consistency, failure recovery, observability, security, cost, and architectural evolution.", rounds: [{ name: "System design", description: "Probe scalability, reliability, data architecture, and explicit trade-offs.", deliveryMode: "system-design", questionCount: 1, questions: [{ text: "Design a multi-region file storage and synchronization service for millions of active users." }] }] },
            { id: "staff-system-design", title: "Staff-level rubric", summary: "Ambiguity, multi-region architecture, migration, organizational constraints, and long-term trade-offs.", jobDescription: "Evaluate staff-level system design: frame ambiguous requirements, quantify scale, design multi-region architecture, plan migrations, manage failure domains, consider security/cost/operability, and communicate long-term trade-offs.", rounds: [{ name: "Architecture discussion", description: "Evaluate technical strategy and architecture under ambiguity and organizational constraints.", deliveryMode: "system-design", questionCount: 1, questions: [{ text: "Design the evolution of a single-region event platform into a multi-region service with strict reliability targets and zero-downtime migration." }] }] },
        ],
        related: ["technical-interview-scorecard-template", "structured-technical-interviews", "technical-assessment-template"],
    },
    {
        surface: "hiring",
        slug: "software-engineer-interview-questions",
        title: "Software Engineer Interview Questions",
        metaTitle: "Software Engineer Interview Questions for Hiring Teams | Evalcue AI",
        description: "Use structured software engineer interview questions that collect evidence on coding, design, debugging, ownership, and engineering judgment.",
        eyebrow: "Questions your team can actually use",
        intro: "Choose the interview signal you need and turn the questions into an editable Evalcue AI Hire assessment draft.",
        roles: ["Software Engineer", "Software Engineer II", "Senior Software Engineer"],
        examples: [
            { id: "problem-solving", title: "Problem solving + debugging", summary: "Reasoning, evidence gathering, hypotheses, testing, and communication.", jobDescription: "Evaluate software engineering problem solving and debugging using production-style scenarios, hypothesis-driven investigation, evidence gathering, testing, and clear communication.", rounds: [{ name: "Problem solving", description: "Evaluate structured debugging and technical reasoning.", deliveryMode: "conversational", questionCount: 3, questions: [{ text: "A service starts returning intermittent 500s after a release. How would you investigate it?" }, { text: "Tell me about a bug where the obvious hypothesis was wrong. What evidence changed your direction?" }, { text: "How do you decide when to add instrumentation versus reproduce locally?" }] }] },
            { id: "coding-design", title: "Coding + design", summary: "Implementation, interfaces, correctness, complexity, tests, and maintainability.", jobDescription: "Evaluate coding and software design: implementation correctness, interfaces, complexity, testing, maintainability, and explaining trade-offs.", rounds: [{ name: "Coding / written", description: "Evaluate implementation quality and reasoning.", deliveryMode: "online-assessment", questionCount: 2, questions: [{ text: "Implement a function that returns the first non-repeating character and explain its time and space complexity." }, { text: "Design a small in-memory rate limiter API and explain how you would test edge cases." }] }] },
            { id: "ownership", title: "Engineering ownership", summary: "Incidents, ambiguity, prioritization, quality, collaboration, and trade-offs.", jobDescription: "Evaluate engineering ownership through incidents, ambiguity, prioritization, quality decisions, collaboration, and balancing technical and product constraints.", rounds: [{ name: "Engineering judgment", description: "Collect evidence of ownership and decision quality.", deliveryMode: "conversational", questionCount: 3, questions: [{ text: "Tell me about a production incident you owned from detection through follow-up." }, { text: "Describe a time you deliberately shipped a simpler solution. What risks did you accept?" }, { text: "How do you handle disagreement on a technical direction when data is incomplete?" }] }] },
        ],
        related: ["technical-interview-scorecard-template", "structured-technical-interviews", "technical-assessment-template"],
    },
    {
        surface: "hiring",
        slug: "structured-technical-interviews",
        title: "Structured Technical Interviews",
        metaTitle: "Structured Technical Interviews for Engineering Hiring | Evalcue AI",
        description: "Design structured technical interviews with consistent competencies, questions, evidence collection, and human-controlled hiring decisions.",
        eyebrow: "Structured interview builder",
        intro: "Pick a structured interview pattern and create it as a draft assessment. Every draft remains editable and human-reviewed before launch.",
        roles: ["Software Engineer", "Backend Engineer", "Senior Software Engineer"],
        examples: [
            { id: "single-round", title: "Focused technical screen", summary: "One consistent conversational round for an early technical signal.", jobDescription: "Run a consistent early technical screen focused on problem solving, practical engineering judgment, debugging, and role-relevant technical depth.", rounds: [{ name: "Technical screen", description: "Collect a consistent early technical signal.", deliveryMode: "conversational", questionCount: 3, questions: [{ text: "Walk through how you would debug an API whose latency doubles only under load." }, { text: "Describe a design decision where you traded simplicity for scalability or vice versa." }, { text: "How do you validate that a change is safe before production rollout?" }] }] },
            { id: "hybrid", title: "Hybrid interview loop", summary: "Conversational + coding + system design rounds with distinct signals.", jobDescription: "Run a structured engineering assessment with separate conversational, coding, and system-design signals so each round measures something meaningfully different.", rounds: [{ name: "Technical interview", description: "Engineering judgment and role depth.", deliveryMode: "conversational", questionCount: 2, questions: [{ text: "Describe a production system you improved and the evidence that showed improvement was needed." }, { text: "How do you reason about reliability when a dependency has weaker availability than your service target?" }] }, { name: "Coding", description: "Implementation quality and reasoning.", deliveryMode: "online-assessment", questionCount: 1, questions: [{ text: "Implement an LRU cache and explain correctness, complexity, and tests." }] }, { name: "System design", description: "Architecture and trade-offs.", deliveryMode: "system-design", questionCount: 1, questions: [{ text: "Design a scalable job-processing platform with retries, priorities, and worker failure recovery." }] }] },
            { id: "senior-loop", title: "Senior technical loop", summary: "Architecture, incidents, design judgment, and influence rather than trivia.", jobDescription: "Evaluate senior engineering ability through architecture, incident leadership, technical judgment, system evolution, reliability, and influence rather than framework trivia.", rounds: [{ name: "Senior engineering discussion", description: "Architecture, ownership, and production judgment.", deliveryMode: "conversational", questionCount: 3, questions: [{ text: "Describe a technical strategy you changed because the system or organization evolved." }, { text: "How would you decide whether to split a service that has become a bottleneck?" }, { text: "Tell me about an incident that changed an engineering practice on your team." }] }] },
        ],
        related: ["technical-interview-scorecard-template", "software-engineer-interview-questions", "system-design-interview-rubric"],
    },
    {
        surface: "hiring",
        slug: "technical-assessment-template",
        title: "Technical Assessment Template",
        metaTitle: "Technical Assessment Template for Software Engineers | Evalcue AI",
        description: "Create an editable technical assessment template for software engineering roles with coding, discussion, and system-design options.",
        eyebrow: "Ready-to-use assessment templates",
        intro: "Choose a template and Evalcue AI Hire creates a draft assessment with real questions. Review it, edit it, and only then invite candidates.",
        roles: ["Backend Engineer", "Frontend Engineer", "Full Stack Engineer"],
        examples: [
            { id: "backend-assessment", title: "Backend assessment", summary: "API/data reasoning plus a practical coding task.", jobDescription: "Assess backend engineering ability across API design, databases, reliability, caching, testing, and implementation quality.", rounds: [{ name: "Backend discussion", description: "API, data, reliability, and production reasoning.", deliveryMode: "conversational", questionCount: 2, questions: [{ text: "Design an API that must safely handle duplicate client retries." }, { text: "A database query regresses from 50ms to 2s after data growth. How would you investigate and fix it?" }] }, { name: "Coding", description: "Implementation and correctness.", deliveryMode: "online-assessment", questionCount: 1, questions: [{ text: "Implement a bounded in-memory cache with LRU eviction and explain how you would make it thread-safe." }] }] },
            { id: "frontend-assessment", title: "Frontend assessment", summary: "UI architecture, performance, accessibility, APIs, and practical coding.", jobDescription: "Assess frontend engineering ability across React/UI architecture, state, performance, accessibility, API integration, testing, and implementation trade-offs.", rounds: [{ name: "Frontend discussion", description: "Architecture, performance, accessibility, and product reasoning.", deliveryMode: "conversational", questionCount: 2, questions: [{ text: "How would you diagnose a page that feels slow even though the API is fast?" }, { text: "Design state management for a complex form with autosave, validation, and optimistic updates." }] }, { name: "Coding / written", description: "Practical implementation reasoning.", deliveryMode: "online-assessment", questionCount: 1, questions: [{ text: "Implement a debounced search component and explain race-condition handling and accessibility considerations." }] }] },
            { id: "fullstack-assessment", title: "Full-stack assessment", summary: "End-to-end feature design across UI, API, data, reliability, and testing.", jobDescription: "Assess full-stack engineering ability across frontend architecture, APIs, data modeling, security, performance, testing, observability, and end-to-end ownership.", rounds: [{ name: "End-to-end design", description: "Design a feature across UI, API, data, and operations.", deliveryMode: "conversational", questionCount: 2, questions: [{ text: "Design an end-to-end file upload feature with progress, retries, permissions, and large-file support." }, { text: "How would you roll out a schema-changing feature safely across frontend and backend versions?" }] }, { name: "Coding", description: "Implementation and reasoning.", deliveryMode: "online-assessment", questionCount: 1, questions: [{ text: "Implement a paginated API client that prevents duplicate requests and stale responses." }] }] },
        ],
        related: ["structured-technical-interviews", "technical-interview-scorecard-template", "software-engineer-interview-questions"],
    },
];

export const resourcePageFor = (surface, slug) => PRODUCT_RESOURCE_PAGES.find((page) => page.surface === surface && page.slug === slug) || null;
export const resourcePathFor = (page) => `/${page.surface === "hiring" ? "hire" : "practice"}/resources/${page.slug}`;
export const resourcePagesForSurface = (surface) => PRODUCT_RESOURCE_PAGES.filter((page) => page.surface === surface);
export const resourcePathsForSurface = (surface) => resourcePagesForSurface(surface).map(resourcePathFor);
export const isProductResourcePath = (pathname = "") => PRODUCT_RESOURCE_PAGES.some((page) => resourcePathFor(page) === pathname);
