export const SEARCH_LANDING_PAGES = [
    {
        slug: "ai-interview-practice",
        path: "/ai-interview-practice",
        title: "AI Interview Practice for Software Engineers",
        metaTitle: "AI Interview Practice for Software Engineers | Evalcue AI",
        description: "Practice realistic software engineering interviews with an adaptive AI interviewer across technical discussion, coding, system design, debugging, and behavioral follow-ups.",
        eyebrow: "AI interview practice",
        intro: "Rehearse the parts of a software engineering interview that are difficult to practice alone: explaining decisions out loud, handling follow-up questions, defending trade-offs, and reviewing where your answers became shallow or unclear.",
        sections: [
            {
                heading: "Practice a conversation, not a static question list",
                body: "Evalcue AI uses the role, job description, and your previous answers as context for follow-up questions. That makes practice closer to an interview conversation where the next question depends on the evidence you have already given.",
                points: ["Role- and job-description-specific prompts", "Adaptive follow-ups based on your answers", "Voice or text technical discussion", "Post-interview feedback and improvement suggestions"],
            },
            {
                heading: "Cover the full software engineering interview loop",
                body: "Technical interviews test different signals. Use separate practice rounds for coding, system design, debugging, backend depth, and behavioral ownership instead of treating every interview as a generic Q&A session.",
                points: ["Coding and problem-solving rounds", "Live system-design discussion with an architecture canvas", "Production-style debugging and engineering judgment", "Behavioral and project-depth follow-ups"],
            },
            {
                heading: "Use evidence from each session to improve the next one",
                body: "The useful output of mock practice is not a single score. Review where requirements were missed, assumptions were unstated, complexity analysis was weak, or technical choices were not justified, then repeat the weak area deliberately.",
                points: ["Transcript and answer review", "Competency-oriented feedback", "Recurring weakness identification", "Progress tracking across practice sessions"],
            },
        ],
        faq: [
            ["What is AI interview practice?", "AI interview practice uses an AI interviewer to simulate interview questions, listen to or read your answers, ask follow-ups, and provide feedback so you can rehearse before a real interview."],
            ["Can I practice technical interviews with AI?", "Yes. Evalcue AI supports software engineering practice across technical discussion, coding, system design, backend topics, debugging, and behavioral questions."],
            ["Is AI interview feedback always correct?", "No. Treat AI feedback as coaching evidence rather than an unquestionable answer key. Validate technical claims and use repeated patterns across sessions to guide deliberate practice."],
        ],
        related: ["ai-mock-interview", "software-engineer-interview-practice", "technical-interview-practice"],
        practiceResource: "software-engineer-mock-interview",
        schema: "WebPage",
    },
    {
        slug: "ai-mock-interview",
        path: "/ai-mock-interview",
        title: "AI Mock Interview for Software Engineers",
        metaTitle: "AI Mock Interview for Software Engineers | Evalcue AI",
        description: "Run an AI mock interview for software engineering roles with adaptive follow-ups, coding, system design, resume and job-description context, and structured feedback.",
        eyebrow: "AI mock interview",
        intro: "Use a realistic mock interview to practice how you think and communicate under follow-up pressure, not just whether you can recall an answer when reading a question by yourself.",
        sections: [
            {
                heading: "Start from the role you are actually interviewing for",
                body: "A backend SDE-2 interview should not look like a frontend graduate interview. Add the target role or job description so the mock interview can emphasize the technical areas and level of depth that matter for that position.",
                points: ["Role and seniority context", "Job-description-aware interview planning", "Resume context when you choose to provide it", "Different round types for different interview signals"],
            },
            {
                heading: "Handle adaptive interviewer follow-ups",
                body: "Strong interviews rarely stop after the first answer. Practice clarifying assumptions, explaining alternatives, responding to edge cases, and defending trade-offs when the interviewer challenges your initial approach.",
                points: ["Clarification questions", "Deeper technical probes", "Trade-off and failure-mode discussion", "Evidence-seeking project follow-ups"],
            },
            {
                heading: "Review the interview while it is still fresh",
                body: "After the session, use the transcript and feedback to identify the specific places where the answer lost structure or technical depth. Repeating one weak round with a clear improvement goal is more useful than collecting disconnected mock interviews.",
                points: ["Immediate feedback", "Answer-level improvement areas", "Technical depth review", "Repeatable practice workflow"],
            },
        ],
        faq: [
            ["How does an AI mock interview work?", "You choose a target role or interview focus, answer questions in a simulated interview, receive adaptive follow-ups, and then review feedback on the evidence and clarity in your responses."],
            ["Can I do a software engineer mock interview online?", "Yes. Evalcue AI is browser-based and supports software engineering mock practice across conversational, coding, and system-design rounds."],
            ["Should I use a mock interview before every real interview?", "Mock interviews are most useful when you have a specific target and enough time to review the feedback, practice the weak area, and repeat it before the real interview."],
        ],
        related: ["ai-interview-practice", "software-engineer-interview-practice", "system-design-interview-practice"],
        practiceResource: "software-engineer-mock-interview",
        schema: "WebPage",
    },
    {
        slug: "software-engineer-interview-practice",
        path: "/software-engineer-interview-practice",
        title: "Software Engineer Interview Practice",
        metaTitle: "Software Engineer Interview Practice with AI | Evalcue AI",
        description: "Practice software engineering interviews with AI across coding, APIs, databases, debugging, system design, reliability, projects, and behavioral ownership.",
        eyebrow: "Software engineer interview practice",
        intro: "Prepare for the complete software engineering interview loop by practicing implementation, design, production reasoning, project depth, and communication as separate signals.",
        sections: [
            {
                heading: "Practice the technical areas interviewers actually probe",
                body: "Software engineering interviews often move between implementation details and production reasoning. Prepare to explain algorithms, APIs, data models, concurrency, caching, reliability, testing, and the decisions behind systems you have built.",
                points: ["Coding and complexity analysis", "API and data-model design", "Databases, caching, queues, and concurrency", "Testing, observability, reliability, and incidents"],
            },
            {
                heading: "Prepare your project and experience stories",
                body: "Experienced-engineer interviews frequently use your own work as the starting point. Practice describing the problem, constraints, your contribution, alternatives considered, measurable outcome, and what you would change now.",
                points: ["Architecture deep dives", "Production incident discussion", "Ownership and collaboration", "Trade-offs and measurable outcomes"],
            },
            {
                heading: "Match practice depth to seniority",
                body: "As seniority increases, interviewers generally expect more explicit trade-off reasoning, ambiguity handling, failure analysis, and system-level judgment. Configure practice around the level you are targeting instead of using the same question depth for every role.",
                points: ["SDE-1 fundamentals", "SDE-2 design and production reasoning", "Senior architecture and ownership", "Role-specific technical depth"],
            },
        ],
        faq: [
            ["What should a software engineer practice before an interview?", "A balanced plan usually includes coding, role-specific technical depth, system or low-level design where relevant, project deep dives, debugging and production reasoning, and behavioral ownership stories."],
            ["Can Evalcue AI use a job description for practice?", "Yes. Job-description context can be used to shape the interview toward the technologies, responsibilities, and seniority described in the role."],
            ["Is this only for backend engineers?", "No. The practice workflow can be configured for backend, frontend, full-stack, platform, and other software engineering roles."],
        ],
        related: ["technical-interview-practice", "coding-interview-practice", "backend-engineer-interview-practice"],
        practiceResource: "software-engineer-mock-interview",
        schema: "TechArticle",
    },
    {
        slug: "technical-interview-practice",
        path: "/technical-interview-practice",
        title: "Technical Interview Practice with AI",
        metaTitle: "Technical Interview Practice with AI for Engineers | Evalcue AI",
        description: "Practice technical interviews with adaptive AI follow-ups across coding, system design, debugging, backend engineering, APIs, databases, reliability, and project depth.",
        eyebrow: "Technical interview practice",
        intro: "Technical interview preparation becomes more useful when you have to explain your reasoning, react to new constraints, and defend decisions instead of only reading model answers.",
        sections: [
            {
                heading: "Turn knowledge into interview-ready explanations",
                body: "Knowing a concept and explaining it under pressure are different skills. Practice stating assumptions, walking through an approach, analyzing complexity, testing edge cases, and communicating why a technical decision fits the constraints.",
                points: ["Reasoning before implementation", "Complexity and edge-case discussion", "Alternative approaches", "Clear technical communication"],
            },
            {
                heading: "Mix implementation with production engineering",
                body: "For experienced roles, technical interviews often extend beyond data structures. Prepare for API design, database behavior, caching, queues, distributed systems, observability, incident debugging, and system evolution.",
                points: ["Algorithms and coding", "APIs and databases", "Distributed systems and reliability", "Debugging and observability"],
            },
            {
                heading: "Use targeted rounds instead of random questions",
                body: "Choose the exact area you need to improve and run a focused mock round. This makes it easier to compare attempts and see whether your reasoning, structure, and technical depth are actually getting better.",
                points: ["Focused practice tracks", "Role-specific prompts", "Adaptive follow-ups", "Reviewable session history"],
            },
        ],
        faq: [
            ["What is the best way to practice a technical interview?", "Combine active problem solving with spoken or written explanation, interviewer-style follow-ups, and a review of your mistakes. Repeating weak areas deliberately is more effective than only reading more questions."],
            ["What technical interview topics can I practice?", "Evalcue AI supports coding, system design, backend engineering, Java-oriented depth, debugging, APIs, databases, reliability, and role-specific technical discussion."],
            ["Can technical interview practice include my resume?", "Yes. When you choose to provide resume context, practice can include project and experience follow-ups in addition to general technical questions."],
        ],
        related: ["software-engineer-interview-practice", "system-design-interview-practice", "coding-interview-practice"],
        practiceResource: "software-engineer-mock-interview",
        schema: "TechArticle",
    },
    {
        slug: "system-design-interview-practice",
        path: "/system-design-interview-practice",
        title: "System Design Interview Practice with AI",
        metaTitle: "System Design Interview Practice with AI | Evalcue AI",
        description: "Practice system design interviews with a live AI interviewer and architecture canvas. Rehearse requirements, APIs, data models, scaling, reliability, and trade-offs.",
        eyebrow: "System design interview practice",
        intro: "Practice the conversation around an architecture, not just the finished diagram. Clarify requirements, sketch the design, explain data flow, and respond when the interviewer pushes on scale, consistency, failures, or trade-offs.",
        sections: [
            {
                heading: "Use a repeatable system design interview structure",
                body: "A clear structure helps you avoid jumping directly into infrastructure. Start with requirements and scale, define APIs and data, propose the high-level architecture, then spend the remaining time on bottlenecks, failures, and explicit trade-offs.",
                points: ["Functional and non-functional requirements", "Capacity and traffic assumptions", "APIs and core data model", "Architecture, bottlenecks, reliability, and trade-offs"],
            },
            {
                heading: "Draw and explain the architecture together",
                body: "Evalcue AI system-design rounds include an architecture canvas so the diagram and discussion evolve together. The interviewer can probe the design while you explain components, dependencies, data movement, and failure handling.",
                points: ["Live architecture canvas", "Context-aware interviewer interjections", "Component and data-flow discussion", "Diagram-aware evaluation context"],
            },
            {
                heading: "Practice the questions that expose shallow designs",
                body: "The difficult part of a system design round is usually the follow-up: what fails first, how data is partitioned, what consistency is required, how retries stay safe, where observability lives, and what changes at ten times the load.",
                points: ["Hotspots and partitioning", "Caching and invalidation", "Retries, idempotency, and queues", "Multi-region, disaster recovery, and observability"],
            },
        ],
        faq: [
            ["How do I practice system design interviews?", "Use a timed problem, clarify requirements first, state scale assumptions, define APIs and data, draw a coherent architecture, and spend meaningful time defending trade-offs and failure handling."],
            ["Can I draw diagrams during Evalcue AI system design practice?", "Yes. System-design rounds use a live architecture canvas alongside the interviewer discussion."],
            ["What system design problems should I practice?", "Common starting points include URL shorteners, notification systems, file storage, chat systems, rate limiting, job processing, feeds, and other services that expose different scaling and consistency trade-offs."],
        ],
        related: ["technical-interview-practice", "backend-engineer-interview-practice", "ai-mock-interview"],
        practiceResource: "system-design-interview-preparation",
        schema: "TechArticle",
    },
    {
        slug: "coding-interview-practice",
        path: "/coding-interview-practice",
        title: "Coding Interview Practice with AI",
        metaTitle: "Coding Interview Practice with AI for Software Engineers | Evalcue AI",
        description: "Practice coding interviews with AI follow-ups on reasoning, implementation, complexity, tests, edge cases, and optimization across common DSA topics.",
        eyebrow: "Coding interview practice",
        intro: "Practice coding as an interview skill: clarify the problem, explain the approach, implement it, test edge cases, analyze complexity, and respond to optimization follow-ups.",
        sections: [
            {
                heading: "Practice the reasoning interviewers hear before the code",
                body: "A correct solution is stronger when the reasoning is clear. State the brute-force approach, identify the bottleneck, choose an appropriate data structure, explain invariants, and call out edge cases before implementation.",
                points: ["Problem clarification", "Approach and data-structure choice", "Correctness reasoning", "Time and space complexity"],
            },
            {
                heading: "Cover the common coding patterns",
                body: "Use focused rounds for arrays and hashing, two pointers, sliding windows, stacks and queues, trees and graphs, heaps, binary search, backtracking, greedy problems, and dynamic programming.",
                points: ["Arrays, strings, and hashing", "Trees and graphs", "Heaps, intervals, and binary search", "Backtracking and dynamic programming"],
            },
            {
                heading: "Finish with tests and follow-up optimization",
                body: "After implementation, explicitly test boundary cases and discuss how the solution changes if inputs are larger, memory is constrained, data arrives as a stream, or concurrency is introduced.",
                points: ["Edge-case tests", "Complexity verification", "Alternative implementations", "Constraint-change follow-ups"],
            },
        ],
        faq: [
            ["How should I practice coding interviews?", "Solve problems under interview-like constraints and explain your thinking as you go. Always finish with complexity analysis, tests, edge cases, and at least one possible follow-up or optimization."],
            ["Does Evalcue AI support coding rounds?", "Yes. Practice can include coding and online-assessment style rounds with interviewer context and post-session feedback."],
            ["Should I memorize coding solutions?", "Memorizing exact solutions is brittle. Learn reusable problem-solving patterns and practice deriving the approach from constraints so you can adapt when the interviewer changes the problem."],
        ],
        related: ["technical-interview-practice", "software-engineer-interview-practice", "backend-engineer-interview-practice"],
        practiceResource: "coding-interview-questions",
        schema: "TechArticle",
    },
    {
        slug: "backend-engineer-interview-practice",
        path: "/backend-engineer-interview-practice",
        title: "Backend Engineer Interview Practice",
        metaTitle: "Backend Engineer Interview Practice with AI | Evalcue AI",
        description: "Practice backend engineering interviews across APIs, databases, transactions, caching, queues, concurrency, distributed systems, reliability, observability, and system design.",
        eyebrow: "Backend interview practice",
        intro: "Prepare for backend interviews that connect code to production systems. Practice API and data design, concurrency, caching, asynchronous workflows, failure handling, observability, and architecture trade-offs.",
        sections: [
            {
                heading: "Go beyond framework trivia",
                body: "Backend interviews are strongest when they test engineering decisions rather than memorized definitions. Practice explaining how requests flow through a service, how data is stored, what happens under concurrency, and how the system behaves when dependencies fail.",
                points: ["REST and API design", "SQL, NoSQL, indexes, and transactions", "Caching and invalidation", "Concurrency and asynchronous processing"],
            },
            {
                heading: "Prepare for distributed-systems follow-ups",
                body: "Be ready to discuss idempotency, retries, queues, partitioning, replication, consistency, rate limiting, backpressure, failover, and how you would observe the system in production.",
                points: ["Retries and idempotency", "Queues and delivery guarantees", "Partitioning and replication", "Metrics, logs, traces, and alerting"],
            },
            {
                heading: "Connect backend depth to system design",
                body: "Backend interviews often transition naturally into system design. Practice making storage and communication choices from access patterns and reliability requirements instead of naming technologies before the problem is clear.",
                points: ["Access-pattern-driven storage choices", "Synchronous vs asynchronous boundaries", "Scalability and failure modes", "Operational and cost trade-offs"],
            },
        ],
        faq: [
            ["What should I study for a backend engineer interview?", "Focus on your primary language, API design, databases and transactions, concurrency, caching, queues, distributed systems, reliability, observability, testing, and system design at the depth expected for your seniority."],
            ["Can I practice Java backend interviews?", "Yes. Evalcue AI already includes Java-oriented practice covering core Java, collections, concurrency, and backend engineering topics."],
            ["Are backend interviews only coding interviews?", "No. Many backend roles combine coding with API and database design, debugging, distributed-systems reasoning, production reliability, and system design."],
        ],
        related: ["system-design-interview-practice", "technical-interview-practice", "debugging-interview-practice"],
        practiceResource: "java-interview-questions",
        schema: "TechArticle",
    },
    {
        slug: "debugging-interview-practice",
        path: "/debugging-interview-practice",
        title: "Debugging Interview Practice for Software Engineers",
        metaTitle: "Debugging Interview Practice for Software Engineers | Evalcue AI",
        description: "Practice software engineering debugging interviews with production-style scenarios, hypothesis-driven investigation, code evidence, tests, and root-cause reasoning.",
        eyebrow: "Debugging interview practice",
        intro: "Debugging interviews test how you investigate uncertainty. Practice forming hypotheses, collecting evidence, narrowing the failure, validating the root cause, and explaining a safe fix instead of guessing from symptoms.",
        sections: [
            {
                heading: "Use a hypothesis-driven debugging process",
                body: "Start by defining the symptom and blast radius. Gather the highest-signal evidence, form a small set of hypotheses, test them in an order that reduces uncertainty quickly, and update the investigation when evidence contradicts the initial theory.",
                points: ["Clarify the symptom and scope", "Collect logs, metrics, traces, and code evidence", "Rank and test hypotheses", "Confirm root cause before proposing the fix"],
            },
            {
                heading: "Practice production-style failure scenarios",
                body: "Useful debugging practice includes intermittent 500s, latency regressions, database slowdowns, race conditions, cache inconsistency, queue backlogs, memory growth, and failures introduced by recent deployments.",
                points: ["Performance regressions", "Data and concurrency bugs", "Dependency and network failures", "Deployment and configuration regressions"],
            },
            {
                heading: "Show how you would prove the fix",
                body: "A debugging answer is incomplete without validation. Explain the test that reproduces the bug, the smallest safe change, regression coverage, rollout strategy, and the monitoring that confirms the production symptom is gone.",
                points: ["Reproduction and regression test", "Root-cause-focused fix", "Safe rollout or rollback plan", "Post-fix monitoring"],
            },
        ],
        faq: [
            ["What is a debugging interview?", "A debugging interview evaluates how you investigate an unfamiliar failure, use evidence, reason about root causes, and validate a fix. It may use a scenario, logs, or an existing codebase rather than a blank coding problem."],
            ["How can I get better at debugging interviews?", "Practice narrating a structured investigation. Avoid jumping immediately to a fix; explain what evidence you would inspect, what each observation would imply, and how you would falsify your hypotheses."],
            ["Does Evalcue AI support debugging assessments?", "Evalcue AI Hire supports production-style multi-file debugging assessments, while candidate practice can be configured around debugging and production-reasoning scenarios."],
        ],
        related: ["backend-engineer-interview-practice", "technical-interview-practice", "software-engineer-interview-practice"],
        practiceResource: "software-engineer-mock-interview",
        schema: "TechArticle",
    },,
    {
        slug: "system-design",
        path: "/system-design",
        title: "System Design Interview Questions & Practice",
        metaTitle: "System Design Interview Questions & Practice | Evalcue AI",
        description: "Practice common system design interview problems with requirements, APIs, data models, architecture, scalability, reliability, and trade-off follow-ups.",
        eyebrow: "System design interview hub",
        intro: "Use this collection to practice system design as an interview conversation. Start from an open-ended problem, clarify requirements, define APIs and data, draw the architecture, then defend the design under scaling and failure follow-ups.",
        sections: [
            {
                heading: "Use one repeatable interview framework",
                body: "A consistent structure prevents you from jumping directly to technologies. Clarify functional and non-functional requirements, estimate scale, define APIs and data, draw the high-level design, then spend the rest of the interview on bottlenecks, failure modes, and trade-offs.",
                points: ["Requirements and scope", "Capacity and traffic assumptions", "APIs and data model", "Architecture, failures, and trade-offs"],
            },
            {
                heading: "Practice problems that expose different design skills",
                body: "Different prompts reveal different strengths. URL shortening emphasizes read-heavy access and ID generation; rate limiting emphasizes distributed coordination; file storage emphasizes metadata and synchronization; notifications emphasize fan-out and retries; payments emphasize correctness and idempotency.",
                points: ["URL shortener", "Distributed rate limiter", "Google Drive-like storage", "Notification and payment systems"],
            },
            {
                heading: "Answer follow-ups, not just the first prompt",
                body: "The real signal in a system design interview often appears after the initial diagram. Practice responding when the interviewer changes traffic, consistency, latency, regional, security, or reliability requirements.",
                points: ["Hot keys and hotspots", "Consistency and replication", "Retries and idempotency", "Multi-region and disaster recovery"],
            },
        ],
        faq: [
            ["What are common system design interview questions?", "Common prompts include URL shorteners, rate limiters, notification systems, file storage, chat systems, feeds, payment systems, job schedulers, and other services that expose scalability and reliability trade-offs."],
            ["How should I structure a system design interview?", "A practical flow is requirements, rough scale estimates, APIs, data model, high-level architecture, key bottlenecks, scaling, reliability, security and observability, followed by explicit trade-offs."],
            ["How long should I spend on the initial architecture?", "Avoid spending the entire interview drawing the first diagram. Build a coherent baseline quickly so there is time for the deeper follow-up discussion where many interview signals appear."],
        ],
        related: ["system-design-interview-practice", "url-shortener-system-design", "rate-limiter-system-design", "google-drive-system-design", "notification-service-system-design"],
        practiceResource: "system-design-interview-preparation",
        schema: "CollectionPage",
    },
    {
        slug: "url-shortener-system-design",
        path: "/system-design/url-shortener",
        title: "Design a URL Shortener",
        metaTitle: "Design a URL Shortener: System Design Interview | Evalcue AI",
        description: "Practice the URL shortener system design interview: requirements, short-code generation, APIs, storage, caching, redirects, hotspots, analytics, and trade-offs.",
        eyebrow: "System design problem",
        intro: "Design a Bitly- or TinyURL-like service that maps long URLs to compact aliases and serves extremely fast redirects. Use the problem to practice read-heavy architecture, unique ID generation, caching, hotspots, and failure handling.",
        sections: [
            {
                heading: "Clarify the requirements before choosing an encoding",
                body: "Start with the core write and redirect flows, then clarify custom aliases, expiry, analytics, authentication, abuse prevention, expected read-to-write ratio, latency, and availability. These decisions change the storage and short-code strategy.",
                points: ["Create a short URL", "Redirect short code to original URL", "Optional custom aliases and expiry", "High availability and low redirect latency"],
            },
            {
                heading: "Design the API, key generation, and read path",
                body: "A typical design separates URL creation from the latency-sensitive redirect path. Compare approaches such as base-62 encoding of generated IDs, random codes with collision checks, or hashes, and explain how uniqueness works under concurrency.",
                points: ["POST /urls and GET /{code}", "Base62 or random short-code generation", "Key-value access pattern", "Cache hot mappings before the primary store"],
            },
            {
                heading: "Deep dive into scale and failure modes",
                body: "The strongest follow-ups cover viral links, cache misses, database partitioning, redirect semantics, analytics that must not slow the redirect, code-generation failure, abuse, and multi-region availability.",
                points: ["Hot-key handling and cache strategy", "Partitioning and replication", "Asynchronous click analytics", "Rate limiting, abuse prevention, and observability"],
            },
        ],
        faq: [
            ["Why is URL shortener a common system design question?", "It has a small functional surface but opens useful discussions about capacity estimation, distributed ID generation, read-heavy storage, caching, database partitioning, availability, and trade-offs."],
            ["Should a URL shortener use SQL or NoSQL?", "Either can work. The important part is the access pattern and scale. The core lookup is usually a simple short-code-to-URL mapping, so explain consistency, indexing, partitioning, operational needs, and why your chosen store fits."],
            ["How do I handle a viral short URL?", "Keep the redirect path cache-friendly, replicate or distribute the cache, avoid synchronous analytics work, and explain how the storage layer and load balancers handle a single extremely hot key."],
        ],
        related: ["system-design", "rate-limiter-system-design", "notification-service-system-design", "system-design-interview-practice"],
        practiceResource: "system-design-interview-questions",
        schema: "TechArticle",
    },
    {
        slug: "rate-limiter-system-design",
        path: "/system-design/rate-limiter",
        title: "Design a Distributed Rate Limiter",
        metaTitle: "Design a Distributed Rate Limiter: System Design Interview | Evalcue AI",
        description: "Practice distributed rate limiter system design across algorithms, APIs, Redis-style shared state, atomicity, sharding, failure modes, and multi-region trade-offs.",
        eyebrow: "System design problem",
        intro: "Design a rate-limiting service that protects APIs across many application servers. The interview tests algorithm choice, distributed state, atomic updates, failure behavior, fairness, and the balance between strictness and availability.",
        sections: [
            {
                heading: "Define what is being limited",
                body: "Clarify whether limits apply per user, API key, IP, organization, endpoint, or a combination. Ask about burst allowance, request cost, response headers, regional scope, latency budget, and what should happen if the limiter is unavailable.",
                points: ["Identity and policy dimensions", "Requests per second or weighted cost", "Burst behavior", "Fail-open versus fail-closed"],
            },
            {
                heading: "Choose the algorithm from the requirements",
                body: "Compare fixed window, sliding window log, sliding window counter, token bucket, and leaky bucket. Explain memory, precision, burst behavior, and how atomicity is maintained when many servers update the same limiter state.",
                points: ["Token bucket for controlled bursts", "Sliding counters for smoother limits", "Atomic shared-state updates", "Local fast path versus centralized state"],
            },
            {
                heading: "Handle distributed and multi-region behavior",
                body: "At scale, discuss sharding by limiter key, Redis or another low-latency state store, local caches, clock assumptions, replication lag, cross-region limits, degraded behavior, configuration distribution, and observability.",
                points: ["Key-based sharding", "Replication and regional limits", "Policy configuration rollout", "Metrics for blocked requests and limiter latency"],
            },
        ],
        faq: [
            ["Which rate limiting algorithm is best for interviews?", "There is no universal best algorithm. Token bucket is a common choice when bursts should be allowed, while sliding-window approaches can enforce smoother limits. State the required behavior and choose accordingly."],
            ["Why is atomicity important in a distributed rate limiter?", "Multiple application servers may check and update the same limit concurrently. Without atomic operations, concurrent requests can all observe stale state and exceed the intended quota."],
            ["Should a rate limiter fail open or fail closed?", "It depends on risk. Consumer APIs may prefer availability and fail open during limiter outages, while security-sensitive or expensive operations may choose stricter behavior. Explain the business trade-off."],
        ],
        related: ["system-design", "url-shortener-system-design", "payment-system-design", "backend-engineer-interview-practice"],
        practiceResource: "system-design-interview-preparation",
        schema: "TechArticle",
    },
    {
        slug: "google-drive-system-design",
        path: "/system-design/google-drive",
        title: "Design Google Drive or Cloud File Storage",
        metaTitle: "Design Google Drive: File Storage System Design Interview | Evalcue AI",
        description: "Practice a Google Drive-like system design covering uploads, metadata, chunking, object storage, versioning, sharing, synchronization, consistency, and reliability.",
        eyebrow: "System design problem",
        intro: "Design a cloud file storage and synchronization service. The problem combines large-object transfer, metadata, permissions, versioning, sync, offline changes, and reliability across devices and regions.",
        sections: [
            {
                heading: "Separate file bytes from file metadata",
                body: "Clarify file-size limits, folders, sharing, versions, offline support, and synchronization. A common design stores large file chunks in object storage while a metadata service owns names, versions, permissions, chunk manifests, and user-visible hierarchy.",
                points: ["Resumable uploads", "Chunked object storage", "Metadata and version records", "Folders, ownership, and sharing"],
            },
            {
                heading: "Design upload, download, and sync flows",
                body: "Discuss multipart or chunked upload sessions, checksums, deduplication if required, pre-signed transfer URLs, download authorization, change logs, client cursors, and how devices learn which files changed.",
                points: ["Upload session API", "Chunk checksum and retry", "Change feed or sync cursor", "Conflict detection and versioning"],
            },
            {
                heading: "Deep dive into consistency and reliability",
                body: "Follow-ups often cover concurrent edits, metadata transactions, lost devices, deleted files, permission changes, chunk durability, multi-region replication, large-file retries, quotas, and disaster recovery.",
                points: ["Metadata consistency", "Conflict resolution", "Durable replicated object storage", "Deletion, retention, and recovery"],
            },
        ],
        faq: [
            ["Why split metadata from object storage?", "Metadata needs transactions, indexes, permissions, and low-latency listing, while large immutable file chunks benefit from scalable object storage. Separating them lets each workload use a suitable storage model."],
            ["How can file uploads resume after failure?", "Upload files in independently addressable chunks, persist an upload-session manifest, verify chunk checksums, and let the client retry only missing or failed chunks before finalizing the version."],
            ["How do multiple devices synchronize changes?", "Maintain an ordered or cursor-based change feed per user or workspace so clients can ask for changes since their last sync point, then resolve conflicts according to the product's consistency rules."],
        ],
        related: ["system-design", "notification-service-system-design", "url-shortener-system-design", "system-design-interview-practice"],
        practiceResource: "system-design-interview-questions",
        schema: "TechArticle",
    },
    {
        slug: "notification-service-system-design",
        path: "/system-design/notification-service",
        title: "Design a Notification Service",
        metaTitle: "Design a Notification Service: System Design Interview | Evalcue AI",
        description: "Practice notification service system design across APIs, fan-out, queues, user preferences, retries, rate limits, providers, idempotency, tracking, and delivery guarantees.",
        eyebrow: "System design problem",
        intro: "Design a platform that sends push, email, and SMS notifications at scale. This problem tests asynchronous processing, fan-out, provider abstraction, user preferences, retries, rate limits, idempotency, and observability.",
        sections: [
            {
                heading: "Clarify channels, urgency, and delivery semantics",
                body: "Ask which channels are supported, whether messages are transactional or bulk, required ordering, delay tolerance, user preferences, quiet hours, templates, localization, deduplication, and whether delivery is at-most-once or at-least-once.",
                points: ["Push, email, and SMS", "Transactional versus bulk traffic", "Preferences and quiet hours", "Priority and delivery expectations"],
            },
            {
                heading: "Use asynchronous fan-out and provider adapters",
                body: "A notification API should validate and persist intent quickly, then queues and workers can expand recipients, render templates, apply preferences and rate limits, and call channel-specific providers without blocking the producer.",
                points: ["Notification API", "Queue or event bus", "Channel-specific workers", "Provider abstraction and fallback"],
            },
            {
                heading: "Design retries without duplicate user impact",
                body: "Discuss idempotency keys, retry schedules, dead-letter queues, provider throttling, per-user limits, delivery status, webhook processing, partial provider outages, and observability across the end-to-end pipeline.",
                points: ["Idempotent delivery attempts", "Exponential backoff and DLQ", "Provider rate limits", "Delivery tracking and alerting"],
            },
        ],
        faq: [
            ["Why use queues in a notification service?", "Queues decouple producers from slower external providers, absorb bursts, enable retries, and let different channels scale independently without making the caller wait for final delivery."],
            ["How do you avoid duplicate notifications?", "Use stable notification or idempotency identifiers, make state transitions atomic, and ensure retried worker operations can recognize an already completed delivery attempt."],
            ["How should provider failures be handled?", "Retry transient failures with backoff, respect provider rate limits, use dead-letter handling for repeated failures, and consider a secondary provider only when product requirements justify the complexity."],
        ],
        related: ["system-design", "payment-system-design", "google-drive-system-design", "system-design-interview-practice"],
        practiceResource: "system-design-interview-questions",
        schema: "TechArticle",
    },
    {
        slug: "payment-system-design",
        path: "/system-design/payment-system",
        title: "Design a Payment System",
        metaTitle: "Design a Payment System: System Design Interview | Evalcue AI",
        description: "Practice payment system design across payment intents, idempotency, ledgers, provider integration, webhooks, retries, reconciliation, consistency, and failure handling.",
        eyebrow: "System design problem",
        intro: "Design a payment platform where correctness matters more than simply maximizing throughput. The interview focuses on idempotency, durable state transitions, money movement records, provider uncertainty, reconciliation, and safe retries.",
        sections: [
            {
                heading: "Model the payment lifecycle explicitly",
                body: "Clarify authorization, capture, refunds, payment methods, currencies, asynchronous provider results, and whether the system moves money itself or orchestrates payment processors. Represent payment state transitions explicitly instead of treating payment as one synchronous API call.",
                points: ["Payment intent and attempt", "Authorize, capture, refund", "Explicit state machine", "Stable idempotency key"],
            },
            {
                heading: "Keep a durable source of financial truth",
                body: "Discuss immutable transaction records or a double-entry-style ledger where appropriate, atomic database updates, unique constraints, outbox patterns, and why cache should never become the authoritative record of money movement.",
                points: ["Durable transaction records", "Atomic state transitions", "Ledger or accounting entries", "Transactional outbox for side effects"],
            },
            {
                heading: "Design for ambiguous provider outcomes",
                body: "Network timeouts can leave the caller unsure whether a provider completed a charge. Explain idempotent provider requests, webhook processing, polling when necessary, reconciliation jobs, duplicate-event handling, and operational tooling for exceptions.",
                points: ["Idempotent retries", "Signed provider webhooks", "Reconciliation", "Audit trails and observability"],
            },
        ],
        faq: [
            ["Why is idempotency critical in payment systems?", "Clients and services retry after timeouts. Without idempotency, the same logical payment can be processed more than once. A stable key lets repeated requests return or continue the same operation safely."],
            ["Should Redis store payment state?", "Redis can help with caching or coordination, but durable payment and ledger state should live in a transactional persistent store designed to preserve correctness across crashes and retries."],
            ["What is reconciliation?", "Reconciliation compares your internal payment records with processor or bank records to find missing, duplicated, delayed, or inconsistent transactions and resolve discrepancies."],
        ],
        related: ["system-design", "rate-limiter-system-design", "notification-service-system-design", "backend-engineer-interview-practice"],
        practiceResource: "system-design-interview-preparation",
        schema: "TechArticle",
    },
    {
        slug: "interview-questions",
        path: "/interview-questions",
        title: "Software Engineering Interview Questions",
        metaTitle: "Software Engineering Interview Questions by Topic | Evalcue AI",
        description: "Prepare for software engineering interviews with focused questions on Java, Spring Boot, Redis, distributed systems, microservices, coding, and system design.",
        eyebrow: "Technical interview question hub",
        intro: "Use topic-specific question sets to identify gaps, then practice the same area in an adaptive interview where follow-ups test whether you can apply the concept rather than only repeat a definition.",
        sections: [
            {
                heading: "Start with your primary backend stack",
                body: "For backend roles, depth in the language and framework matters. Practice Java fundamentals and concurrency, Spring Boot service behavior, Redis caching patterns, database and API reasoning, and the failure modes you have seen in production.",
                points: ["Java and JVM", "Spring Boot", "Redis and caching", "APIs and databases"],
            },
            {
                heading: "Add distributed-systems reasoning",
                body: "Experienced-engineer interviews increasingly ask what happens across service boundaries. Be prepared for consistency, replication, queues, idempotency, retries, partitioning, backpressure, observability, and partial failure.",
                points: ["Distributed systems", "Microservices", "Queues and asynchronous processing", "Reliability and observability"],
            },
            {
                heading: "Turn each answer into a follow-up conversation",
                body: "Definitions are only the beginning. For every topic, practice a scenario, a trade-off, a failure mode, and a question about when you would choose a different approach.",
                points: ["Definition", "Production scenario", "Trade-off", "Failure and debugging follow-up"],
            },
        ],
        faq: [
            ["How should I use interview question lists?", "Use them diagnostically. Answer aloud or in writing, mark weak topics, then practice those areas in scenarios or mock interviews instead of memorizing a long list of canned answers."],
            ["Which backend interview topics matter most?", "Your primary language, framework, APIs, databases, caching, concurrency, distributed systems, reliability, testing, observability, and system design are common areas for experienced backend roles."],
            ["How deep should interview answers be?", "Match the role level. Junior answers may focus on correct concepts; experienced roles usually require production examples, trade-offs, failure behavior, and reasons for choosing one approach over another."],
        ],
        related: ["java-interview-questions-guide", "spring-boot-interview-questions", "redis-interview-questions", "distributed-systems-interview-questions", "microservices-interview-questions"],
        practiceResource: "software-engineer-mock-interview",
        schema: "CollectionPage",
    },
    {
        slug: "java-interview-questions-guide",
        path: "/interview-questions/java",
        title: "Java Interview Questions for Software Engineers",
        metaTitle: "Java Interview Questions for Backend Engineers | Evalcue AI",
        description: "Prepare for Java interviews across JVM, collections, equality, generics, exceptions, concurrency, executors, CompletableFuture, memory, and backend scenarios.",
        eyebrow: "Java interview questions",
        intro: "Prepare for Java interviews by connecting language fundamentals to production behavior. Strong answers explain not only what an API does, but also memory, concurrency, correctness, and trade-offs.",
        sections: [
            {
                heading: "Core Java questions",
                body: "Be ready to explain Java semantics precisely and connect them to examples from real code.",
                points: ["Why is Java pass-by-value, including object references?", "equals() vs == and the hashCode contract", "Interface vs abstract class", "Checked vs unchecked exceptions and when to use each"],
            },
            {
                heading: "Collections and concurrency questions",
                body: "Backend interviews frequently probe data structure behavior and thread safety rather than surface-level syntax.",
                points: ["How does HashMap work and what causes collisions?", "ConcurrentHashMap vs synchronizedMap", "synchronized vs Lock", "ExecutorService, Future, and CompletableFuture trade-offs"],
            },
            {
                heading: "JVM and production follow-ups",
                body: "For experienced roles, prepare to discuss heap versus stack, garbage collection, memory leaks, thread pools, blocking calls, immutability, and how you would diagnose a Java service under load.",
                points: ["JDK vs JRE vs JVM", "Heap, stack, and object lifetime", "GC pauses and allocation pressure", "Diagnosing high CPU, memory, or thread contention"],
            },
        ],
        faq: [
            ["What Java topics are most common in backend interviews?", "Collections, equality and hashing, exceptions, generics, concurrency, thread pools, CompletableFuture, JVM memory, garbage collection, immutability, and practical Spring/backend scenarios are common."],
            ["Should I memorize HashMap internals?", "Understand the behavior and why it matters: hashing, bucket selection, collisions, equality, resizing, complexity, and thread-safety limitations. Memorizing implementation trivia without reasoning is less useful."],
            ["How do I practice Java interview follow-ups?", "After answering a concept question, add a scenario: concurrency, performance, failure, testing, or API design. Evalcue AI's Java practice track can use adaptive follow-ups instead of a fixed question list."],
        ],
        related: ["interview-questions", "spring-boot-interview-questions", "distributed-systems-interview-questions", "backend-engineer-interview-practice"],
        practiceResource: "java-interview-questions",
        schema: "TechArticle",
    },
    {
        slug: "spring-boot-interview-questions",
        path: "/interview-questions/spring-boot",
        title: "Spring Boot Interview Questions for Backend Engineers",
        metaTitle: "Spring Boot Interview Questions for Backend Engineers | Evalcue AI",
        description: "Prepare for Spring Boot interviews across dependency injection, auto-configuration, REST APIs, transactions, JPA, validation, security, testing, Actuator, and resilience.",
        eyebrow: "Spring Boot interview questions",
        intro: "Spring Boot interviews often test whether you understand what the framework is doing around your application. Prepare to explain dependency injection, transactions, persistence, web request handling, testing, security, and production operations.",
        sections: [
            {
                heading: "Framework and dependency-injection questions",
                body: "Start with the container and configuration model, then connect it to how services are composed and tested.",
                points: ["How does Spring Boot auto-configuration work?", "@Component, @Service, @Repository, and @Bean", "Constructor injection vs field injection", "What happens during application startup?"],
            },
            {
                heading: "Web, data, and transaction questions",
                body: "Backend interviews commonly move from controllers into persistence and transaction boundaries.",
                points: ["@RestController and request validation", "@Transactional behavior and common pitfalls", "JPA N+1 queries and fetch strategies", "Exception handling with @ControllerAdvice"],
            },
            {
                heading: "Production and testing follow-ups",
                body: "For experienced roles, prepare for Actuator, metrics, security filters, integration testing, connection pools, retries, circuit breakers, asynchronous work, and how you would investigate a slow Spring service.",
                points: ["Unit vs slice vs integration tests", "Actuator health and metrics", "Spring Security request flow", "Diagnosing latency and database bottlenecks"],
            },
        ],
        faq: [
            ["What Spring Boot areas should I study for interviews?", "Dependency injection, auto-configuration, REST controllers, validation, exception handling, transactions, JPA, testing, security, configuration, Actuator, and production troubleshooting are high-value areas."],
            ["Why can @Transactional fail unexpectedly?", "Common reasons include self-invocation bypassing the proxy, wrong propagation assumptions, exceptions that do not trigger rollback by default, or performing work outside the proxied transaction boundary."],
            ["Is Spring Boot knowledge enough for a backend interview?", "Usually not. Combine it with Java, SQL and databases, API design, caching, concurrency, distributed systems, testing, observability, and system design."],
        ],
        related: ["interview-questions", "java-interview-questions-guide", "redis-interview-questions", "microservices-interview-questions"],
        practiceResource: "java-interview-questions",
        schema: "TechArticle",
    },
    {
        slug: "redis-interview-questions",
        path: "/interview-questions/redis",
        title: "Redis Interview Questions for Backend Engineers",
        metaTitle: "Redis Interview Questions: Caching, Persistence & Scaling | Evalcue AI",
        description: "Prepare for Redis interviews across data structures, caching, TTLs, eviction, persistence, replication, clustering, pipelining, locks, cache stampede, and failure modes.",
        eyebrow: "Redis interview questions",
        intro: "Redis interview questions become much more useful when tied to production caching and coordination problems. Prepare to explain data structures, eviction, persistence, replication, clustering, and what can go wrong under load.",
        sections: [
            {
                heading: "Core Redis questions",
                body: "Understand why Redis is fast, its major data structures, expiration behavior, and the difference between using it as a cache and using it as a durable data store.",
                points: ["Why is Redis fast?", "Strings, hashes, lists, sets, sorted sets, and streams", "TTL and lazy/active expiration", "RDB vs AOF persistence"],
            },
            {
                heading: "Caching interview questions",
                body: "Caching questions usually probe invalidation and failure behavior rather than just GET and SET.",
                points: ["Cache-aside vs write-through", "Cache stampede and request coalescing", "Hot keys and TTL jitter", "Eviction policies and memory pressure"],
            },
            {
                heading: "Scaling and distributed follow-ups",
                body: "Prepare for replication, Sentinel, Cluster, pipelining, transactions or Lua for atomicity, distributed-lock caveats, and how the application behaves when Redis is slow or unavailable.",
                points: ["Replication and failover", "Redis Cluster and hash slots", "Pipelining vs transactions", "Graceful degradation during cache failure"],
            },
        ],
        faq: [
            ["What Redis questions are common in backend interviews?", "Data structures, TTLs, eviction, persistence, cache-aside, stampede prevention, hot keys, pipelining, replication, clustering, distributed locks, and failure handling are common."],
            ["Should Redis be the source of truth?", "It depends on the use case, but for many application caches Redis is intentionally not the durable source of truth. Explain persistence, recovery, consistency, and what happens if Redis data is lost."],
            ["How do you prevent cache stampede?", "Common techniques include locking or single-flight refresh, stale-while-revalidate, probabilistic early refresh, and adding TTL jitter so many hot keys do not expire simultaneously."],
        ],
        related: ["interview-questions", "distributed-systems-interview-questions", "microservices-interview-questions", "backend-engineer-interview-practice"],
        practiceResource: "software-engineer-mock-interview",
        schema: "TechArticle",
    },
    {
        slug: "distributed-systems-interview-questions",
        path: "/interview-questions/distributed-systems",
        title: "Distributed Systems Interview Questions",
        metaTitle: "Distributed Systems Interview Questions for Engineers | Evalcue AI",
        description: "Prepare for distributed systems interviews across consistency, replication, partitioning, consensus, queues, idempotency, retries, clocks, failures, and observability.",
        eyebrow: "Distributed systems interview questions",
        intro: "Distributed systems interviews test whether you can reason about partial failure and trade-offs. Prepare to explain what happens when machines disagree, messages are duplicated, networks partition, or dependencies become slower than your service target.",
        sections: [
            {
                heading: "Consistency and data questions",
                body: "Be precise about what consistency guarantee the application needs before choosing replication or storage behavior.",
                points: ["Strong vs eventual consistency", "Leader-based replication", "Partitioning and hotspot avoidance", "Quorums and read/write trade-offs"],
            },
            {
                heading: "Messaging and failure questions",
                body: "Queues and service calls introduce retries, duplicates, ordering, backpressure, and ambiguous outcomes.",
                points: ["At-most-once vs at-least-once delivery", "Idempotency and deduplication", "Retry storms and exponential backoff", "Backpressure and dead-letter handling"],
            },
            {
                heading: "Coordination and operations follow-ups",
                body: "Experienced candidates should discuss clocks, leases, leader election, consensus at a conceptual level, split brain, failure detection, observability, and graceful degradation.",
                points: ["CAP trade-offs in a real scenario", "Leader election and consensus", "Clock skew and timeouts", "Metrics, tracing, and failure-domain isolation"],
            },
        ],
        faq: [
            ["What should I study for distributed systems interviews?", "Focus on consistency, replication, partitioning, queues, retries, idempotency, consensus concepts, time and clocks, failure detection, backpressure, observability, and concrete trade-offs."],
            ["Do I need to memorize CAP theorem?", "Know what network partitions imply and how a system chooses behavior during them. Interviewers usually get more signal from a concrete consistency/availability scenario than from reciting the theorem."],
            ["What is the most important distributed-systems mindset?", "Assume partial failure. A remote call can be slow, fail, succeed after your timeout, or be retried. Design protocols and state transitions so the system remains understandable under those conditions."],
        ],
        related: ["interview-questions", "microservices-interview-questions", "redis-interview-questions", "system-design"],
        practiceResource: "system-design-interview-preparation",
        schema: "TechArticle",
    },
    {
        slug: "microservices-interview-questions",
        path: "/interview-questions/microservices",
        title: "Microservices Interview Questions for Backend Engineers",
        metaTitle: "Microservices Interview Questions for Backend Engineers | Evalcue AI",
        description: "Prepare for microservices interviews across service boundaries, communication, data ownership, sagas, idempotency, discovery, resilience, observability, deployment, and trade-offs.",
        eyebrow: "Microservices interview questions",
        intro: "Microservices interviews should be about boundaries and operational trade-offs, not simply naming infrastructure. Prepare to explain when services should be separated, how they communicate, who owns data, and how failures are contained.",
        sections: [
            {
                heading: "Service-boundary questions",
                body: "Start from domain ownership and change patterns rather than splitting a system by technical layers.",
                points: ["How do you choose a service boundary?", "When should a monolith stay a monolith?", "Database per service and data ownership", "API contracts and versioning"],
            },
            {
                heading: "Communication and consistency questions",
                body: "Prepare to compare synchronous calls with events or queues and explain how multi-service workflows remain correct.",
                points: ["REST/gRPC vs asynchronous messaging", "Saga patterns and compensating actions", "Idempotency and duplicate events", "Outbox pattern and reliable event publication"],
            },
            {
                heading: "Reliability and operations follow-ups",
                body: "A microservice architecture adds operational cost. Discuss timeouts, retries, circuit breakers, service discovery, tracing, deployment, configuration, schema evolution, and incident debugging across dependencies.",
                points: ["Timeout and retry budgets", "Circuit breakers and bulkheads", "Distributed tracing", "Independent deployment and rollback"],
            },
        ],
        faq: [
            ["What are common microservices interview questions?", "Expect service boundaries, communication styles, data ownership, distributed transactions, sagas, idempotency, service discovery, resilience, observability, deployment, and when not to use microservices."],
            ["When should you avoid microservices?", "If domain boundaries are unclear, the team is small, independent scaling and deployment are not needed, or operational complexity would dominate the benefits, a modular monolith may be the better choice."],
            ["How do microservices handle transactions across services?", "Prefer local transactions per service and coordinate workflows with patterns such as sagas, idempotent messages, durable events, and compensating actions rather than relying on broad distributed transactions."],
        ],
        related: ["interview-questions", "distributed-systems-interview-questions", "spring-boot-interview-questions", "backend-engineer-interview-practice"],
        practiceResource: "software-engineer-mock-interview",
        schema: "TechArticle",
    }
];

export const searchLandingPageForPath = (pathname = "") => SEARCH_LANDING_PAGES.find((page) => page.path === pathname) || null;
export const searchLandingPageForSlug = (slug = "") => SEARCH_LANDING_PAGES.find((page) => page.slug === slug) || null;
export const searchLandingPaths = () => SEARCH_LANDING_PAGES.map((page) => page.path);
